config/routes.rb
Sapphire::Application.routes.draw do
  devise_for :users

  resources :table_schemas do
    post :create_tag, :on => :collection
  end

  resources :tag_table_schemas, :only => [:show, :destroy] do
    post :dump_xml, :on => :collection
    post :dump_nsf, :on => :collection
  end

  resources :recommend_configs do
    get :batch_edit, :on => :collection
    post :batch_update, :on => :collection

    get :copy_new, :on => :collection
    post :copy_create, :on => :collection
  end

  resources :deploy_data do
    get :help, :on => :collection
  end

  resources :deploy_machines

  resources :auto_deploy do
    get :deploy, :on => :collection
    get :rollback, :on => :collection
    get :finish, :on => :collection
  end

  match "home/help"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/table_schema.rb
class TableSchema
  include Mongoid::Document
  include Mongoid::Timestamps

  field :table, type: String
  field :version, type: String
  field :owner, type: String

  embeds_many :table_fields
  accepts_nested_attributes_for :table_fields, :allow_destroy => true

  has_many :recommend_configs

  validates_presence_of :table, :version, :owner, :table_fields
  validates_uniqueness_of :table, :case_sensitive => false

  index :table => 1
  index :owner => 1

  attr_accessible :table_fields_attributes, :table, :version, :owner

  after_save :sort_table_fields

  def sort_table_fields
    temp_table_fields = self.table_fields.each do |field|
      if field.group == "key"
        field.group = " key"
      end
    end

    temp_table_fields.sort! do |left, right|
      [left.group, left.id] <=> [right.group, right.id]
    end

    temp_table_fields.each do |field|
      if field.group == " key"
        field.group = "key"
      end
    end

    self.table_fields = temp_table_fields
  end

  def group_fields
    group_fields_hash = {}
    self.table_fields.each do |field|
      if group_fields_hash.has_key?(field.group)
        group_fields_hash[field.group] << field
      else
        group_fields_hash[field.group] = [field]
      end
    end

    return group_fields_hash
  end

  def groups
    groups = []
    self.table_fields.each do |table_field|
      groups << table_field.group
    end
    groups.uniq
  end
end

app/controllers/table_schemas_controller.rb
# coding: utf-8

class TableSchemasController < ApplicationController
  before_filter :authenticate_user!

  def index
    if !params[:owner]
      @table_schemas = TableSchema.order_by([[:owner, :asc], [:id, :asc]])
      @tag_table_schemas = TagTableSchema.order_by([[:table, :asc], [:id, :asc]])
    else
      @table_schemas = TableSchema.where(:owner=>params[:owner]).order_by([[:owner, :asc], [:id, :asc]])
      @tag_table_schemas = TagTableSchema.where(:owner=>params[:owner]).order_by([[:table, :asc], [:id, :asc]])
    end
  end

  def show
    @table_schema = TableSchema.find(params[:id])
  end

  def new
    @table_schema = TableSchema.new
  end

  def edit
    @table_schema = TableSchema.find(params[:id])
  end

  def create
    @table_schema = TableSchema.new(params[:table_schema])

    if @table_schema.save
      redirect_to @table_schema, notice: 'Table schema was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @table_schema = TableSchema.find(params[:id])
    table_schema_old = @table_schema.dup

    if @table_schema.update_attributes(params[:table_schema])
      table_schema_new = @table_schema.dup
      #获取更新详情：增加，删除，修改的field
      diff_fields = get_diff_fields(table_schema_old.table_fields, table_schema_new.table_fields)
      if !diff_fields
        #TODO: recover to old table_schema, 下面的恢复方式无效
        #@table_schema.update_attributes(table_schema_old.attributes)
        flash[:error] = 'Table schema was updated, but recommend config data updated failed. Reason: diff_field failed!'
        redirect_to @table_schema and return
      end

      #更新已经存在的数据
      update_recommend_configs(diff_fields, table_schema_old, @table_schema)

      redirect_to @table_schema, notice: 'Table schema was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @table_schema = TableSchema.find(params[:id])
    @table_schema.destroy

    redirect_to table_schemas_url
  end

  def create_tag
    @table_schema = TableSchema.find(params[:table_schema][:id])
    @tag_table_schema = TagTableSchema.new
    @tag_table_schema.clone_with_table_schema(@table_schema)
    @tag_table_schema.version = params[:table_schema][:tag_version]

    tag_table_schema_find = TagTableSchema.where(:table=>@tag_table_schema.table,
                                                 :version=>@tag_table_schema.version)
    
    if tag_table_schema_find.count > 0
      flash[:error] = "Create table: [#{@tag_table_schema.table}] tag: [#{@tag_table_schema.version}] failed. Reason: it has exist."
      redirect_to table_schemas_url and return
    end

    #要先save tag_table_schema, 然后再save tag_recommend_config
    #否则tag_recommend_config.tag_table_schema_id为nil
    if !@tag_table_schema.save
      flash[:error] = "Create table: [#{@tag_table_schema.table}] tag: [#{@tag_table_schema.version}] failed. Reason: save table schema failed."
      redirect_to table_schemas_url and return
    end

    @table_schema.recommend_configs.each do |recommend_config|
      recommend_config_dup = recommend_config.dup
      recommend_config_dup.attributes.delete("table_schema_id")
      recommend_config_dup.attributes.delete("created_at")
      recommend_config_dup.attributes.delete("updated_at")
      tag_recommend_config = TagRecommendConfig.new(recommend_config_dup.attributes)
      @tag_table_schema.tag_recommend_configs << tag_recommend_config
      tag_recommend_config.save
    end

    redirect_to table_schemas_url, notice: "Create table: [#{@tag_table_schema.table}] tag: [#{@tag_table_schema.version}] successed."
  end

  #def create_tag
  #  @table_schema = TableSchema.find(params[:table_schema][:id])
  #  table_schema_dup = @table_schema.dup
  #  #这里不会递归拷贝构造子对象, 需要手动拷贝table_fields
  #  @tag_table_schema = TagTableSchema.new(table_schema_dup.attributes)
  #  @tag_table_schema.table_fields = @table_schema.table_fields.dup
  #  @tag_table_schema.version = params[:table_schema][:tag_version]

  #  #要先save tag_table_schema, 然后再save tag_recommend_config
  #  #否则tag_recommend_config.tag_table_schema_id为nil
  #  #TODO: 如果save失败, 需要用notice通知
  #  @tag_table_schema.save

  #  @table_schema.recommend_configs.each do |recommend_config|
  #    recommend_config_dup = recommend_config.dup
  #    recommend_config_dup.attributes.delete("table_schema_id")
  #    tag_recommend_config = TagRecommendConfig.new(recommend_config_dup.attributes)
  #    @tag_table_schema.tag_recommend_configs << tag_recommend_config
  #    tag_recommend_config.save
  #  end

  #  redirect_to table_schemas_url
  #end

  private

  def update_recommend_configs(diff_fields, table_schema_old, table_schema_new)
    table_schema_new.recommend_configs.each do |recommend_config|
      #只拷贝table_fields对应的属性, 接下来只修改这些属性
      #如果使用recommend_config.attributes, 会拷贝全部属性
      #比如_id, update_at, table_schema_id等，接下来可能会误操作这些属性
      update_attributes = clone_attributes(recommend_config, table_schema_old)
      if !update_attributes
        #TODO: 跳过这条数据继续处理其他数据，但这条数据如何处理？
        #TODO: 在日志中记录这条数据的相关信息
        next
      end
      #更新field的数据, 也可以新增group
      diff_fields[:remove].each do |table_field|
        update_attributes[table_field["group"]].delete(table_field["name"])
      end

      diff_fields[:add].each do |table_field|
        #新增group
        if !update_attributes.has_key?(table_field["group"])
          update_attributes[table_field["group"]] = {}
        end
        update_attributes[table_field["group"]][table_field["name"]] = table_field["default_value"]
      end

      diff_fields[:modify].each do |table_field_pair|
        ts_old = table_field_pair["old"]
        ts_new = table_field_pair["new"]
        #先插入新的字段, 然后再删除旧的字段
        if !update_attributes[ts_new["group"]].has_key?(ts_old["name"]) 
          update_attributes[ts_new["group"]][ts_new["name"]] = ""
        else
          update_attributes[ts_new["group"]][ts_new["name"]] = update_attributes[ts_new["group"]][ts_old["name"]]
          update_attributes[ts_new["group"]].delete(ts_old["name"])
        end
      end

      logger.debug diff_fields
      logger.debug recommend_config.attributes
      logger.debug update_attributes

      recommend_config.update_attributes(update_attributes)

      #删除空的group
      remove_attributes = []
      update_attributes.each do |key, value|
        if value.length == 0
          remove_attributes << key
        end
      end

      remove_attributes.each do |remove_attribute|
        recommend_config.remove_attribute(remove_attribute)
      end

      logger.debug recommend_config.attributes
      logger.debug remove_attributes

      recommend_config.save
    end
  end

  def get_diff_fields(ts_olds, ts_news)
    diff_fields = {:add=>[], :remove=>[], :modify=>[]}

    ts_news.each do |ts_new|
      is_find = false
      ts_olds.each do |ts_old|
        if ts_new["_id"] == ts_old["_id"]
          is_find = true
          #不支持更新group的操作
          if ts_new["group"] != ts_old["group"]
            return nil
          end
          if ts_new["name"] != ts_old["name"]
            diff_fields[:modify] << {"old"=>ts_old, "new"=>ts_new}
          end
          break
        end
      end

      if !is_find
        diff_fields[:add] << ts_new
      end
    end

    ts_olds.each do |ts_old|
      is_find = false
      ts_news.each do |ts_new|
        if ts_new["_id"] == ts_old["_id"]
          is_find = true
          break
        end
      end

      if !is_find
        diff_fields[:remove] << ts_old
      end
    end

    return diff_fields
  end
end

app/helpers/table_schemas_helper.rb
module TableSchemasHelper
  def get_options(option_string)
    option_array = option_string.split(',')
    option_array.each do |option|
      option.strip!
    end
    option_array.map {|o| [o, o]}
  end
end

app/views/table_schemas/_create_tag.html.haml
%div{:id=>"myModalCreateTag#{table_schema.id}", :class=>"modal hide fade", :tabindex=>"-1", :role=>"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    %button.close{:type=>"button", "data-dismiss"=>"modal", "aria-hidden"=>"true"}= "&times;".html_safe
    %h3#myModalLabel Create New Tag
  .modal-body
    = form_for table_schema, :url=>create_tag_table_schemas_path, :method=>:post, :html=>{:class=>"form-horizontal"} do |f|
      = f.hidden_field :id, :value=>table_schema.id

      .control-group
        = f.label :table, :class=>"control-label"
        .controls
          = f.text_field :table, :disabled=>"disabled"
    
      .control-group
        = f.label :version, :class=>"control-label"
        .controls
          = f.text_field :version, :disabled=>"disabled"
    
      .control-group
        = f.label :owner, :class=>"control-label"
        .controls
          = f.text_field :owner, :disabled=>"disabled"

      .control-group
        = label :table_schema, :tag_version, :class=>"control-label"
        .controls
          / 不依赖对象，手动组合二级form结构!
          = text_field :table_schema, :tag_version

      .control-group
        .controls
          = f.submit "Create", :class=>"btn btn-success"
          %button{:class=>"btn", "data-dismiss"=>"modal", "aria-hidden"=>"true"} Cancel

app/views/table_schemas/_dump_nsf.html.haml
%div{:id=>"myModalDumpNsf#{tag_table_schema.id}", :class=>"modal hide fade", :tabindex=>"-1", :role=>"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    %button.close{:type=>"button", "data-dismiss"=>"modal", "aria-hidden"=>"true"}= "&times;".html_safe
    %h3#myModalLabel Dump Data to NSF
  .modal-body
    = form_for tag_table_schema, :url=>dump_nsf_tag_table_schemas_path, :method=>:post, :html=>{:class=>"form-horizontal"} do |f|
      = f.hidden_field :id, :value=>tag_table_schema.id

      .control-group
        = f.label :table, :class=>"control-label"
        .controls
          = f.text_field :table, :disabled=>"disabled"
    
      .control-group
        = f.label :version, :class=>"control-label"
        .controls
          = f.text_field :version, :disabled=>"disabled"
    
      .control-group
        = f.label :owner, :class=>"control-label"
        .controls
          = f.text_field :owner, :disabled=>"disabled"

      .control-group
        = label :tag_table_schema, :file_name, :class=>"control-label"
        .controls
          / 不依赖对象，手动组合二级form结构!
          = text_field :tag_table_schema, :file_name, :value=>"#{tag_table_schema.table}_#{tag_table_schema.version}.nsf"

      .control-group
        .controls
          = f.submit "Create", :class=>"btn btn-success"
          %button{:class=>"btn", "data-dismiss"=>"modal", "aria-hidden"=>"true"} Cancel

app/views/table_schemas/_dump_xml.html.haml
%div{:id=>"myModalDumpXml#{tag_table_schema.id}", :class=>"modal hide fade", :tabindex=>"-1", :role=>"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    %button.close{:type=>"button", "data-dismiss"=>"modal", "aria-hidden"=>"true"}= "&times;".html_safe
    %h3#myModalLabel Dump Data to XML
  .modal-body
    = form_for tag_table_schema, :url=>dump_xml_tag_table_schemas_path, :method=>:post, :html=>{:class=>"form-horizontal"} do |f|
      = f.hidden_field :id, :value=>tag_table_schema.id

      .control-group
        = f.label :table, :class=>"control-label"
        .controls
          = f.text_field :table, :disabled=>"disabled"
    
      .control-group
        = f.label :version, :class=>"control-label"
        .controls
          = f.text_field :version, :disabled=>"disabled"
    
      .control-group
        = f.label :owner, :class=>"control-label"
        .controls
          = f.text_field :owner, :disabled=>"disabled"

      .control-group
        = label :tag_table_schema, :file_name, :class=>"control-label"
        .controls
          / 不依赖对象，手动组合二级form结构!
          = text_field :tag_table_schema, :file_name, :value=>"#{tag_table_schema.table}_#{tag_table_schema.version}.xml"

      .control-group
        .controls
          = f.submit "Create", :class=>"btn btn-success"
          %button{:class=>"btn", "data-dismiss"=>"modal", "aria-hidden"=>"true"} Cancel

app/views/table_schemas/_form.html.haml
= nested_form_for @table_schema, :html => {:class=>"form-horizontal"} do |f|
  - if @table_schema.errors.any?
    #error_explanation
      %h2
        = pluralize(@table_schema.errors.count, "error")
        prohibited this table_schema from being saved:

      %ul
      - @table_schema.errors.full_messages.each do |msg|
        %li= msg

  .control-group
    = f.label :table, :class=>"control-label"
    .controls
      = f.text_field :table

  .control-group
    = f.label :version, :class=>"control-label"
    .controls
      = f.text_field :version, :value=>"trunk"

  .control-group
    = f.label :owner, :class=>"control-label"
    .controls
      = f.select :owner, [["online","online"], ["offline","offline"], ["flow","flow"], ["sandbox","sandbox"]]

  .control-group
    = f.fields_for :table_fields do |fields|
      .well
        .row
          .span2.offset7
            = fields.link_to_remove "Remove this field", :class=>"btn btn-small btn-danger"
        .row
          .span4
            .control-group
              = fields.label :group
              = fields.text_field :group
              = fields.label :label
              = fields.text_field :label
              = fields.label :name
              = fields.text_field :name
          .span4
            .control-group
              = fields.label :default_value
              = fields.text_field :default_value
              = fields.label :help_text
              = fields.text_field :help_text
              = fields.label :field_type
              = fields.select :field_type, [["input","input"], ["select","select"]]
        .control-group
          = fields.label :option_value
          = fields.text_field :option_value, :class=>"input-xxlarge"
    = f.link_to_add "Add a table field", :table_fields, :class=>"btn btn-small btn-primary"

  .control-group
    .controls
      = f.submit :class=>"btn btn-success"
      = link_to 'Back', table_schemas_path, :class=>"btn"

app/views/table_schemas/edit.html.haml
.row
  .span3
    = render "shared/repo_sidebar"

  .span9
    %section.page-content
      %h3 Editing table schema
      
      = render 'form'

app/views/table_schemas/index.html.haml
.row
  .span3
    = render "shared/repo_sidebar"

  .span9
    %section.page-content
      .row
        .span2.offset7
          =link_to "New Table", new_table_schema_path, :class=>"btn btn-primary"

      %p
        %span.label.label-important Trunk
      
      %table.table.table-striped
        %tr
          %th id
          %th table
          %th version
          %th owner
          %th update time
          %th operation
      
        - if @table_schemas
          - @table_schemas.each do |table_schema|
            %tr
              %td= table_schema.id
              %td= table_schema.table
              %td= table_schema.version
              %td= table_schema.owner
              %td= table_schema.updated_at.to_s[0..-7]
              %td
                %a{:href=>"#myModalCreateTag#{table_schema.id}", :role=>"button", :class=>"btn btn-small btn-warning", "data-toggle"=>"modal"} Tag
                = render :partial=>"create_tag", :locals=>{:table_schema=>table_schema}
                = link_to 'Show', table_schema, :class=>"btn btn-small"
                = link_to 'Edit', edit_table_schema_path(table_schema), :class=>"btn btn-small btn-info"
                = link_to 'Destroy', table_schema, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger"


      %p
        %span.label.label-important Tags

      %table.table.table-striped
        %tr
          %th id
          %th table
          %th version
          %th owner
          %th update time
          %th operation
      
        - if @tag_table_schemas
          - @tag_table_schemas.each do |tag_table_schema|
            %tr
              %td= tag_table_schema.id
              %td= tag_table_schema.table
              %td= tag_table_schema.version
              %td= tag_table_schema.owner
              %td= tag_table_schema.updated_at.to_s[0..-7]
              %td
                %a{:href=>"#myModalDumpXml#{tag_table_schema.id}", :role=>"button", :class=>"btn btn-small btn-success", "data-toggle"=>"modal"} XML
                = render :partial=>"dump_xml", :locals=>{:tag_table_schema=>tag_table_schema}
                %a{:href=>"#myModalDumpNsf#{tag_table_schema.id}", :role=>"button", :class=>"btn btn-small btn-success", "data-toggle"=>"modal"} NSF
                = render :partial=>"dump_nsf", :locals=>{:tag_table_schema=>tag_table_schema}
                = link_to 'Show', tag_table_schema, :class=>"btn btn-small"
                = link_to 'Destroy', tag_table_schema, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger"

app/views/table_schemas/new.html.haml
.row
  .span3
    = render "shared/repo_sidebar"

  .span9
    %section.page-content
      %h3 New table
      
      = render 'form'

app/views/table_schemas/show.html.haml
.row
  .span3
    = render "shared/repo_sidebar"

  .span9
    %section.page-content
      %h3 Showing table schema

      = form_for @table_schema, :html => {:class=>"form-horizontal"} do |f|
        .control-group
          = f.label :table, :class=>"control-label"
          .controls
            = f.text_field :table, :disabled=>"disabled"
      
        .control-group
          = f.label :version, :class=>"control-label"
          .controls
            = f.text_field :version, :disabled=>"disabled"
      
        .control-group
          = f.label :owner, :class=>"control-label"
          .controls
            = f.text_field :owner, :disabled=>"disabled"
      
        .control-group
          = f.fields_for :table_fields do |fields|
            .well
              .row
                .span4
                  .control-group
                    = fields.label :group
                    = fields.text_field :group, :disabled=>"disabled"
                    = fields.label :label
                    = fields.text_field :label, :disabled=>"disabled"
                    = fields.label :name
                    = fields.text_field :name, :disabled=>"disabled"
                .span4
                  .control-group
                    = fields.label :default_value
                    = fields.text_field :default_value, :disabled=>"disabled"
                    = fields.label :help_text
                    = fields.text_field :help_text, :disabled=>"disabled"
                    = fields.label :field_type
                    = fields.text_field :field_type, :disabled=>"disabled"
              .control-group
                = fields.label :option_value
                = fields.text_field :option_value, :class=>"input-xxlarge", :disabled=>"disabled"

        .control-group
          .controls
            = link_to 'Edit', edit_table_schema_path(@table_schema), :class=>"btn btn-info"
            = link_to 'Back', table_schemas_path, :class=>"btn"