config/routes.rb
Sapphire::Application.routes.draw do
  devise_for :users

  resources :table_schemas do
    post :create_tag, :on => :collection
  end

  resources :tag_table_schemas, :only => [:show, :destroy] do
    post :dump_xml, :on => :collection
    post :dump_nsf, :on => :collection
  end

  resources :recommend_configs do
    get :batch_edit, :on => :collection
    post :batch_update, :on => :collection

    get :copy_new, :on => :collection
    post :copy_create, :on => :collection
  end

  resources :deploy_data do
    get :help, :on => :collection
  end

  resources :deploy_machines

  resources :auto_deploy do
    get :deploy, :on => :collection
    get :rollback, :on => :collection
    get :finish, :on => :collection
  end

  match "home/help"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/deploy_data_controller.rb
# coding: utf-8
require 'xmlsimple'

class DeployDataController < ApplicationController
  before_filter :authenticate_user!

  def index
    @deploy_data = DeployDatum.order_by([[:id, :asc]])
  end

  def show
    deploy_data = DeployDatum.all
    deploy_data.each do |datum|
      if datum.status == Setting.deploy_datum_status.ready
        datum.update_attributes(:status=>Setting.deploy_datum_status.new)
      end
    end

    @deploy_datum = DeployDatum.find(params[:id])
    if @deploy_datum.status == Setting.deploy_datum_status.new
      @deploy_datum.update_attributes(:status=>Setting.deploy_datum_status.ready)
      session[:deploy_datum_id] = @deploy_datum.id
    end
  end

  def new
    @deploy_datum = DeployDatum.new
    @our_package_hash = get_release_package
  end

  def edit
    @deploy_datum = DeployDatum.find(params[:id])
    @our_package_hash = get_release_package
  end

  def create
    @deploy_datum = DeployDatum.new(params[:deploy_datum])
    @deploy_datum.user = current_user

    if @deploy_datum.save
      redirect_to @deploy_datum, notice: '创建上线数据成功'
    else
      redirect_to new_deploy_datum_url, notice: '上线单需要至少包括一个Package'
      #render action: "new"
    end
  end

  def update
    @deploy_datum = DeployDatum.find(params[:id])

    if @deploy_datum.update_attributes(params[:deploy_datum])
      redirect_to @deploy_datum, notice: '修改上线数据成功'
    else
      render action: "edit"
    end
  end

  def destroy
    @deploy_datum = DeployDatum.find(params[:id])
    @deploy_datum.destroy

    redirect_to deploy_data_url
  end

  def help
  end

  private

  def get_release_package
    doc = RestClient.get(Setting.release_address)
    dom_tree = XmlSimple.xml_in(doc)
    link_tree = dom_tree["body"][0]["ul"][0]["li"]
    package_hash = {}
    link_tree.each do |link|
      package = link["a"][0]["href"]
      pos = (package =~ /-\d+\.\d+\.\d+\.\d+\.tar\.gz/)
      next if !pos
      package_name = package[0...pos]

      if package_hash.has_key?(package_name)
        package_hash[package_name] << package
      else
        package_hash[package_name] = [package]
      end
    end

    package_names = [Setting.package_name.rec_package, Setting.package_name.rerank_package, Setting.package_name.site_package, Setting.package_name.item_package, Setting.package_name.trim_package, Setting.package_name.query_package, Setting.package_name.aliguess_package, Setting.package_name.filter_package, Setting.package_name.indepsite_package, Setting.package_name.ibcf_package, Setting.package_name.taobao_package]

    our_package_hash = {}
    package_names.each do |package_name|
      if package_hash.has_key?(package_name)
        package_list = package_hash[package_name]
        if package_list.size <= 20
          our_package_hash[package_name] = package_list
        else
          our_package_hash[package_name] = package_list[package_list.size-20...package_list.size]
        end
      end
    end

    return our_package_hash
  end
end

app/helpers/deploy_data_helper.rb
module DeployDataHelper
  def get_package_option(package_name)
    options = [[nil, nil]]
    if @our_package_hash.has_key?(package_name)
      options += @our_package_hash[package_name].map {|o| [o, o]}
    end
    return options
  end
end

app/views/deploy_data/_edit_form.html.haml
= form_for @deploy_datum, :url=>deploy_datum_path(@deploy_datum), :method=>:put, :html=>{:class=>"form-horizontal"} do |f|
  - if @deploy_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@deploy_datum.errors.count, "error")} prohibited this deploy_datum from being saved:"
      %ul
        - @deploy_datum.errors.full_messages.each do |msg|
          %li= msg

  = render :partial=>"form_input", :locals=>{:f=>f}

  .control-group
    .controls
      = f.submit '下一步', :class=>"btn btn-info"

app/views/deploy_data/_form_input.html.haml
.control-group
  .control-label
    = f.label :title
  .controls
    = f.text_field :title, :class=>"input-xxlarge"

.control-group
  .control-label
    = f.label :svn_config
  .controls
    = f.select :svn_config, [[nil, nil],[Setting.protocol.config.value, Setting.protocol.config.value]], {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :rec_package
  .controls
    = f.select :rec_package, get_package_option(Setting.package_name.rec_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :rerank_package
  .controls
    = f.select :rerank_package, get_package_option(Setting.package_name.rerank_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :site_package
  .controls
    = f.select :site_package, get_package_option(Setting.package_name.site_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :item_package
  .controls
    = f.select :item_package, get_package_option(Setting.package_name.item_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :trim_package
  .controls
    = f.select :trim_package, get_package_option(Setting.package_name.trim_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :query_package
  .controls
    = f.select :query_package, get_package_option(Setting.package_name.query_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :aliguess_package
  .controls
    = f.select :aliguess_package, get_package_option(Setting.package_name.aliguess_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :filter_package
  .controls
    = f.select :filter_package, get_package_option(Setting.package_name.filter_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :indepsite_package
  .controls
    = f.select :indepsite_package, get_package_option(Setting.package_name.indepsite_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :ibcf_package
  .controls
    = f.select :ibcf_package, get_package_option(Setting.package_name.ibcf_package), {}, {:class=>"span5"}

.control-group
  .control-label
    = f.label :taobao_package
  .controls
    = f.select :taobao_package, get_package_option(Setting.package_name.taobao_package), {}, {:class=>"span5"}

app/views/deploy_data/_new_form.html.haml
= form_for @deploy_datum, :url=>deploy_data_path, :method=>:post, :html=>{:class=>"form-horizontal"} do |f|
  - if @deploy_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@deploy_datum.errors.count, "error")} prohibited this deploy_datum from being saved:"
      %ul
        - @deploy_datum.errors.full_messages.each do |msg|
          %li= msg

  = render :partial=>"form_input", :locals=>{:f=>f}

  .control-group
    .controls
      = f.submit '下一步', :class=>"btn btn-info"

app/views/deploy_data/_show.html.haml
%table.table.table-striped
  %tr
    %th 名称
    %th 地址

  %tr
    %td Title:
    %td= @deploy_datum.title

  %tr
    %td Svn config:
    %td= @deploy_datum.svn_config

  %tr
    %td Rec package:
    %td= @deploy_datum.rec_package

  %tr
    %td Rerank package:
    %td= @deploy_datum.rerank_package

  %tr
    %td Site package:
    %td= @deploy_datum.site_package

  %tr
    %td Item package:
    %td= @deploy_datum.item_package

  %tr
    %td Trim package:
    %td= @deploy_datum.trim_package

  %tr
    %td Query package:
    %td= @deploy_datum.query_package

  %tr
    %td Aliguess package:
    %td= @deploy_datum.aliguess_package

  %tr
    %td Filter package:
    %td= @deploy_datum.filter_package

  %tr
    %td Indepsite package:
    %td= @deploy_datum.indepsite_package

  %tr
    %td Ibcf package:
    %td= @deploy_datum.ibcf_package

  %tr
    %td Taobao package:
    %td= @deploy_datum.taobao_package

app/views/deploy_data/edit.html.haml
.row
  .span3
    = render "shared/deploy_sidebar"

  .span9
    %section.page-content
      %h3 修改上线单

      = render 'edit_form'

app/views/deploy_data/help.html.haml
.row
  .span3
    = render "shared/deploy_sidebar"

  .span9
    %section.page-content
      %h3 自动化部署操作流程

      = link_to '新建上线单', new_deploy_datum_path, :class=>"btn btn-primary"
      = "->"
      = link_to '确认上线单', "#", :class=>"btn btn-info"
      = "->"
      = link_to '自动化部署', "#", :class=>"btn btn-danger"
      = "->"
      = link_to '上线完成', "#", :class=>"btn btn-success"

app/views/deploy_data/index.html.haml
.row
  .span3
    = render "shared/deploy_sidebar"

  .span9
    %section.page-content
      %h3 上线单列表

      %table.table.table-striped
        %tr
          %th 编号
          %th 标题
          %th 状态
          %th 创建人
          %th 更新时间
          %th 操作
      
        - @deploy_data.each do |deploy_datum|
          %tr
            %td= deploy_datum.id
            %td= deploy_datum.title
            %td= deploy_datum.status
            %td= deploy_datum.user ? deploy_datum.user.name : ""
            %td= deploy_datum.updated_at.to_s[0..-7]
            %td
              = link_to 'Show', deploy_datum, :class=>"btn btn-small"
              = link_to 'Edit', edit_deploy_datum_path(deploy_datum), :class=>"btn btn-small btn-info"
              = link_to 'Destroy', deploy_datum, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-small btn-danger"
      
      %br
      
      = link_to '新建上线单', new_deploy_datum_path, :class=>"btn btn-primary"

app/views/deploy_data/new.html.haml
.row
  .span3
    = render "shared/deploy_sidebar"

  .span9
    %section.page-content
      %h3 新建上线单

      = render 'new_form'

app/views/deploy_data/show.html.haml
.row
  .span3
    = render "shared/deploy_sidebar"

  .span9
    %section.page-content
      %h3 确认上线单

      = render "show"

      = link_to "上一步", edit_deploy_datum_path(@deploy_datum), :class=>"btn btn-info"
      = link_to "下一步", auto_deploy_index_path, :class=>"btn btn-info"