config/routes.rb
Sapphire::Application.routes.draw do
  devise_for :users

  resources :table_schemas do
    post :create_tag, :on => :collection
  end

  resources :tag_table_schemas, :only => [:show, :destroy] do
    post :dump_xml, :on => :collection
    post :dump_nsf, :on => :collection
  end

  resources :recommend_configs do
    get :batch_edit, :on => :collection
    post :batch_update, :on => :collection

    get :copy_new, :on => :collection
    post :copy_create, :on => :collection
  end

  resources :deploy_data do
    get :help, :on => :collection
  end

  resources :deploy_machines

  resources :auto_deploy do
    get :deploy, :on => :collection
    get :rollback, :on => :collection
    get :finish, :on => :collection
  end

  match "home/help"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/recommend_config.rb
class RecommendConfig
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :table_schema

  validates_presence_of :table_schema_id

  index :table_schema_id => 1
end

app/controllers/recommend_configs_controller.rb
# coding: utf-8

class RecommendConfigsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @table_schema = TableSchema.find_by(:table=>params[:table])
    @recommend_configs = @table_schema.recommend_configs.page(params[:page])
  end

  def show
    @table_schema = TableSchema.find_by(:table=>params[:table])
    @recommend_config = RecommendConfig.find(params[:id])

    respond_to do |format|
      format.html
      format.js {render :layout => false}
    end
  end

  def new
    @table_schema = TableSchema.find_by(:table=>params[:table])
    @recommend_config = RecommendConfig.new    #just for test use
  end

  def edit
    @table_schema = TableSchema.find_by(:table=>params[:table])
    @recommend_config = RecommendConfig.find(params[:id])
  end

  def create
    @recommend_config = RecommendConfig.new(params[params[:table]])

    if validate_present?(@recommend_config, params[:table])
      flash[:error] = 'Created recommend config failed. Reason: recommend config has existed.'
      redirect_to recommend_configs_url(:owner=>params[:owner], :table=>params[:table]) and return
    end

    if @recommend_config.save
      redirect_to recommend_config_url(@recommend_config, :owner=>params[:owner], :table=>params[:table]), notice: 'Recommend config was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @recommend_config = RecommendConfig.find(params[:id])

    if @recommend_config.update_attributes(params[:recommend_config])
      redirect_to recommend_config_url(@recommend_config, :owner=>params[:owner], :table=>params[:table]), notice: 'Recommend config was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @recommend_config = RecommendConfig.find(params[:id])
    @recommend_config.destroy

    redirect_to recommend_configs_url(:owner=>params[:owner], :table=>params[:table])
  end

  def batch_edit
    @table_schema = TableSchema.find_by(:table=>params[:table])
  end

  def batch_update
    @table_schema = TableSchema.find(params[:table_schema][:id])
    group = params[:table_field][:group]
    name = params[:table_field][:name]
    value = params[:table_field][:value]
    @table_schema.recommend_configs.each do |recommend_config|
      update_attributes = clone_attributes(recommend_config, @table_schema)
      if !update_attributes
        #TODO: 跳过这条数据继续处理其他数据，但这条数据如何处理？
        #TODO: 在日志中记录这条数据的相关信息
        next
      end
      update_attributes[group][name] = value
      recommend_config.update_attributes(update_attributes)

      #必须在完整attributes的基础上做修改，下面的方式是不行的
      #recommend_config.update_attributes(group=>{name=>value})
    end

    redirect_to recommend_configs_url(:owner=>@table_schema.owner,
                                      :table=>@table_schema.table)
  end

  def copy_new
    @table_schema = TableSchema.find_by(:table=>params[:table])
    @recommend_config = RecommendConfig.find(params[:id])
  end

  def copy_create
    @recommend_config = RecommendConfig.new(params[params[:table]])

    if validate_present?(@recommend_config, params[:table])
      flash[:error] = 'Created recommend config failed. Reason: recommend config has existed.'
      redirect_to recommend_configs_url(:owner=>params[:owner], :table=>params[:table]) and return
    end

    if @recommend_config.save
      redirect_to recommend_config_url(@recommend_config, :owner=>params[:owner], :table=>params[:table]), notice: 'Recommend config was successfully created.'
    else
      render action: "new"
    end
  end

  private

  def validate_present?(recommend_config, table)
    key_group_hash = {}
    @table_schema = TableSchema.find_by(:table=>table)
    @table_schema.group_fields["key"].each do |table_field|
      key_group_hash[table_field.name] = recommend_config["key"][table_field.name]
    end
    rc_find = RecommendConfig.where(:key=>key_group_hash)
    !rc_find.empty?
  end
end

app/helpers/recommend_configs_helper.rb
module RecommendConfigsHelper
    def get_owner_first_table(owner)
        table_schemas = TableSchema.where(:owner=>owner)
        table_schemas.length == 0 ? nil : table_schemas[0].table
    end

    def get_owner_all_tables(owner)
        table_schemas = TableSchema.where(:owner=>owner)
    end
end

app/views/recommend_configs/_copy_new_form.html.haml
= form_tag copy_create_recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"form-horizontal" do
  = fields_for "#{@table_schema.table}" do |f|
    = f.hidden_field :table_schema_id, :value=>@table_schema.id
  .accordion#accordion2
    - @table_schema.group_fields.each do |group, fields|
      .accordion-group
        .accordion-heading
          %a.accordion-toggle{"data-toggle"=>"collapse", "data-parent"=>"#accordion2", :href=>"#collapse#{group}"}= "#{group.upcase} GROUP"
        .accordion-body.collapse.in{:id=>"collapse#{group}"}
          .accordion-inner
            - fields.each do |field|
              = fields_for "#{@table_schema.table}[#{field.group}]" do |f|
                .control-group
                  .control-label
                    = f.label field.label
                  .controls
                    - if field.field_type == "select"
                      = f.select field.name, get_options(field.option_value), :selected=>@recommend_config[field.group][field.name], :class=>"input-xxlarge"
                    - else
                      = f.text_field field.name, :value=>@recommend_config[field.group][field.name], :class=>"input-xxlarge"
                  - if field.help_text and field.help_text != ""
                    .controls
                      = "( #{field.help_text} )"

  .control-group
    .controls
      = submit_tag "Create Config", :class=>"btn btn-success"
      = link_to 'Back', recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn"

app/views/recommend_configs/_edit_form.html.haml
= form_for @recommend_config, :url=>recommend_config_path(@recommend_config, :owner=>params[:owner], :table=>params[:table]), :method=>:put, :html=>{:class=>"form-horizontal"} do |form|
  = form.hidden_field :table_schema_id, :value=>@table_schema.id
  .accordion#accordion2
    - @table_schema.group_fields.each do |group, fields|
      .accordion-group
        .accordion-heading
          %a.accordion-toggle{"data-toggle"=>"collapse", "data-parent"=>"#accordion2", :href=>"#collapse#{group}"}= "#{group.upcase} GROUP"
        .accordion-body.collapse.in{:id=>"collapse#{group}"}
          .accordion-inner
            - fields.each do |field|
              /= debug "#{group}    #{field.name}    #{@recommend_config[field.group][field.name]}"
              = form.fields_for group, @recommend_config[group] do |f|
                .control-group
                  .control-label
                    = f.label field.name
                  .controls
                    - if field.field_type == "select"
                      = f.select field.name, get_options(field.option_value), :selected=>@recommend_config[group][field.name], :class=>"input-xxlarge"
                    - else
                      = f.text_field field.name, :value=>@recommend_config[group][field.name], :class=>"input-xxlarge"

  .control-group
    .controls
      = form.submit "Update Config", :class=>"btn btn-success"
      = link_to 'Back', recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn"

app/views/recommend_configs/_form.html.haml
= form_tag recommend_configs_path, :class=>"form-horizontal" do
  .accordion#accordion2
    - divide_group_fields.each do |group, fields|
      .accordion-group
        .accordion-heading
          %a.accordion-toggle{"data-toggle"=>"collapse", "data-parent"=>"#accordion2", :href=>"#collapse#{group}"}= "#{group} config"
        .accordion-body.collapse.in{:id=>"collapse#{group}"}
          .accordion-inner
            - fields.each do |field|
              = fields_for "#{@table_schema.table}[#{field.group}]" do |f|
                .control-group
                  .control-label
                    = f.label field[:label]
                  .controls
                    = f.text_field field[:name]

  .control-group
    .controls
      = submit_tag "Create", :class=>"btn btn-success"
      = link_to 'Back', recommend_configs_path, :class=>"btn"

app/views/recommend_configs/_new_form.html.haml
= form_tag recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"form-horizontal" do
  = fields_for "#{@table_schema.table}" do |f|
    = f.hidden_field :table_schema_id, :value=>@table_schema.id
  .accordion#accordion2
    - @table_schema.group_fields.each do |group, fields|
      .accordion-group
        .accordion-heading
          %a.accordion-toggle{"data-toggle"=>"collapse", "data-parent"=>"#accordion2", :href=>"#collapse#{group}"}= "#{group.upcase} GROUP"
        .accordion-body.collapse.in{:id=>"collapse#{group}"}
          .accordion-inner
            - fields.each do |field|
              = fields_for "#{@table_schema.table}[#{field.group}]" do |f|
                .control-group
                  .control-label
                    = f.label field[:label]
                  .controls
                    - if field[:field_type] == "select"
                      = f.select field[:name], get_options(field[:option_value]), :class=>"input-xxlarge"
                    - else
                      = f.text_field field[:name], :value=>field[:default_value], :class=>"input-xxlarge"
                  - if field[:help_text] and field[:help_text] != ""
                    .controls
                      = "( #{field[:help_text]} )"

  .control-group
    .controls
      = submit_tag "Create Config", :class=>"btn btn-success"
      = link_to 'Back', recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn"

app/views/recommend_configs/_select_field.html.erb
<script>
  $(function(){
    var group_fields = Array()
    <% @table_schema.group_fields.each do |group, fields| %>
      var js_fields = Array()
      <% fields.each do |field| %>
        js_fields.push(<%= "\"#{field.name}\"".html_safe %>)
      <% end %>
      group_fields[<%= "\"#{group}\"".html_safe %>] = js_fields
    <% end %>
    $('#table_field_group').click(function(){
      $('#table_field_name').empty()
      var $group_select = $('#table_field_group option:selected')
      for (i in group_fields[$group_select.text()]){
        var field = group_fields[$group_select.text()][i]
        var field_string = "<option value='" + field + "'>" + field + "</option>"
        var $field_option = $(field_string)
        $('#table_field_name').append($field_option)
      };
    });
  });
</script>

app/views/recommend_configs/_show_modal.html.haml
%div{:id=>"myModalShowAjax", :class=>"modal hide fade custom-width-modal", :tabindex=>"-1", :role=>"dialog", "aria-labelledby"=>"myModalLabel", "aria-hidden"=>"true"}
  .modal-header
    %button.close{:type=>"button", "data-dismiss"=>"modal", "aria-hidden"=>"true"}= "&times;".html_safe
    %h3#myModalLabel Showing Config
  .modal-body
    = form_for @recommend_config, :html=>{:class=>"form-horizontal"} do |form|
      - @table_schema.group_fields.each do |group, fields|
        %legend= "#{group.upcase} GROUP"
        - fields.each do |field|
          = form.fields_for group, @recommend_config[group] do |f|
            .control-group
              .control-label
                = f.label field[:name]
              .controls
                = f.text_field field[:name], :value=>@recommend_config[group][field[:name]], :class=>"input-xxlarge", :disabled=>"disabled"
    
      .control-group
        .controls
          = link_to 'Edit', edit_recommend_config_path(@recommend_config, :owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-info"
          %button{:class=>"btn", "data-dismiss"=>"modal", "aria-hidden"=>"true"} Cancel

app/views/recommend_configs/batch_edit.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      %h3 Batch Update

      = form_for @table_schema, :url=>batch_update_recommend_configs_path, :method=>:post, :html=>{:class=>"form-horizontal"} do |f|
        = f.hidden_field :id, :value=>@table_schema.id

        .control-group
          = f.label :table, :class=>"control-label"
          .controls
            = f.text_field :table, :disabled=>"disabled"
      
        .control-group
          = label :table_field, :group, :class=>"control-label"
          .controls
            /= text_field :table_field, :group
            = select :table_field, :group, @table_schema.groups.map {|o| [o, o]}

        .control-group
          = label :table_field, :name, :class=>"control-label"
          .controls
            = select :table_field, :name, @table_schema.group_fields[@table_schema.groups[0]].map {|o| [o.name, o.name]}

        .control-group
          = label :table_field, :value, :class=>"control-label"
          .controls
            = text_field :table_field, :value

        .control-group
          .controls
            = f.submit "Update", :class=>"btn btn-success"
            = link_to 'Back', recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn"

      = render "select_field"

app/views/recommend_configs/copy_new.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      %h3 Copy Create Config

      = render 'copy_new_form'

app/views/recommend_configs/edit.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      %h3 Editing Config

      = render 'edit_form'

app/views/recommend_configs/index.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      .row
        .span2.offset5
          =link_to "Batch Update", batch_edit_recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-success"
        .span2
          =link_to "New Config", new_recommend_config_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-primary"
      %ul.nav.nav-tabs
        - get_owner_all_tables(params[:owner]).each do |table_schema|
          %li{:class => (request.url=~/#{table_schema.table}/ ? "active" : nil)}
            = link_to table_schema.table, recommend_configs_path(:owner=>params[:owner], :table=>table_schema.table)
      
      %table.table.table-striped
        %tr
          %th id
          - @table_schema.table_fields.each do |field|
            - if field[:group] == "key"
              %th= field[:label]
          %th operation
      
        - @recommend_configs.each do |config|
          %tr
            %td= config.id
            - @table_schema.table_fields.each do |field|
              - if field[:group] == "key" and config["key"]
                %td= config["key"][field[:name]]
            %td
              = link_to 'Show', recommend_config_path(config, :owner=>params[:owner], :table=>params[:table]), :remote=>true, :class=>"btn btn-small"
              = link_to 'Edit', edit_recommend_config_path(config, :owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-small btn-info"
              = link_to 'Copy', copy_new_recommend_configs_path(:id=>config.id, :owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-small btn-primary"
              = link_to 'Destroy', recommend_config_path(config, :owner=>params[:owner], :table=>params[:table]), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-small btn-danger"

      = paginate @recommend_configs

      #show-ajax

app/views/recommend_configs/new.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      %h3 New Config
      
      = render 'new_form'

app/views/recommend_configs/show.html.haml
.row
  .span3
    = render "shared/editor_sidebar"

  .span9
    %section.page-content
      %h3 Showing Config

      = form_for @recommend_config, :html=>{:class=>"form-horizontal"} do |form|
        - @table_schema.group_fields.each do |group, fields|
          %legend= "#{group.upcase} GROUP"
          - fields.each do |field|
            = form.fields_for group, @recommend_config[group] do |f|
              .control-group
                .control-label
                  = f.label field[:name]
                .controls
                  = f.text_field field[:name], :value=>@recommend_config[group][field[:name]], :class=>"input-xxlarge", :disabled=>"disabled"
      
        .control-group
          .controls
            = link_to 'Edit', edit_recommend_config_path(@recommend_config, :owner=>params[:owner], :table=>params[:table]), :class=>"btn btn-info"
            = link_to 'Back', recommend_configs_path(:owner=>params[:owner], :table=>params[:table]), :class=>"btn"

app/views/recommend_configs/show.js.erb
$(".page-content #show-ajax").empty().append('<%= escape_javascript(render 'show_modal') %>');
$("#myModalShowAjax").modal("show")