config/routes.rb
Sapphire::Application.routes.draw do
  devise_for :users

  resources :table_schemas do
    post :create_tag, :on => :collection
  end

  resources :tag_table_schemas, :only => [:show, :destroy] do
    post :dump_xml, :on => :collection
    post :dump_nsf, :on => :collection
  end

  resources :recommend_configs do
    get :batch_edit, :on => :collection
    post :batch_update, :on => :collection

    get :copy_new, :on => :collection
    post :copy_create, :on => :collection
  end

  resources :deploy_data do
    get :help, :on => :collection
  end

  resources :deploy_machines

  resources :auto_deploy do
    get :deploy, :on => :collection
    get :rollback, :on => :collection
    get :finish, :on => :collection
  end

  match "home/help"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_flash_messages.html.haml
- if flash and flash.any?
  - flash.each do |key, value|
    - if :success == key
      .alert-box
        .alert.alert-success
          %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert"}= "&times;".html_safe
          = value
    - elsif :error == key
      .alert-box
        .alert.alert-error
          %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert"}= "&times;".html_safe
          = value
    - else
      .alert-box
        .alert.alert-info
          %button{:type=>"button", :class=>"close", "data-dismiss"=>"alert"}= "&times;".html_safe
          = value

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "配置&部署中心 - 云推荐"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .deploy_mask
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          .nav-collapse.collapse
            .row
              .span6
                %ul.nav
                  %li{:class => (controller_name=="home" and action_name=="index"?"active":nil)}= link_to "首页", root_path
                  %li{:class => (controller_name=="recommend_configs"?"active":nil)}= link_to "配置管理", recommend_configs_path(:owner=>"online", :table=>get_owner_first_table("online"))
                  %li{:class => (controller_name=="table_schemas"?"active":nil)}= link_to "数据表管理", table_schemas_path
                  %li{:class => ((controller_name=="deploy_data" or controller_name=="deploy_machines" or controller_name=="auto_deploy") ? "active":nil)}= link_to "自动化部署", help_deploy_data_path
                  %li{:class => (controller_name=="home" and action_name=="help"?"active":nil)}= link_to "帮助", home_help_path
              - if user_signed_in?
                .offset3.span3
                  %ul.nav
                    %li= link_to "欢迎您，#{current_user.name}", "#"
                    %li= link_to "退出", destroy_user_session_path, :method => :delete
              - else
                .offset4.span2
                  %ul.nav
                    %li= link_to "登录", new_user_session_path
                    %li= link_to "注册", "#"
                    /%li= link_to "注册", new_user_registration_path

    
    /%header.jumbotron.subhead
    /  .container
    /    %h2 配置&部署中心
    /    %p.lead Move fast, and break things.

    .container
      = render "layouts/flash_messages"
      = yield

    .footer
      .container
        %p © Aliyun 2013